### ISSUE TITLE
Configurable queues based on env variables

### ISSUE THREAD

**Issue by fridex** [selinon/selinonlib#7]
Add support for parametrizing queues would be cool:
```yaml
tasks:
  - name: FooTask
    import: my.module
    queue: "{DEPLOY_QUEUE_PREFIX}footask"
```

`DEPLOY_QUEUE_PREFIX` could be `deployment1_`
